// created on: Dec 24, 2014
package droolsexample
 // list any import classes here.
import com.pht.drools.ItemCity
import com.pht.drools.ItemCity.City;
import com.pht.drools.ItemCity.Type
import java.math.BigDecimal;
import com.pht.drools.Utility
import java.math.BigDecimal;
 // declare any global variables here
 dialect "java"
 query "typeofitem==MEDICINES"
     $item: ItemCity(typeofItem==ItemCity.Type.MEDICINES)
 end
 function  String  printmessage(String messafge){
   return messafge;
 }
 declare Location
     thing : String
     location : String
 end

 rule "Pune Medicine Item"
     when item : ItemCity (purchaseCity == ItemCity.City.PUNE, typeofItem == ItemCity.Type.MEDICINES)
     then BigDecimal tax = new BigDecimal(0.0); item.setLocalTax(tax.multiply(item.getSellPrice()));
     System.out.println(printmessage("测试打印！！！！"));
 end

 rule "Pune Groceries Item"
    when item : ItemCity(purchaseCity == ItemCity.City.PUNE, typeofItem == ItemCity.Type.GROCERIES)

     then BigDecimal tax = new BigDecimal(2.0); item.setLocalTax(tax.multiply(item.getSellPrice()));Utility.help();
 end
